version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: supermarket-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - supermarket-network

  backend:
    image: ${DOCKER_USERNAME}/supermarket-backend:latest
    container_name: supermarket-backend
    restart: unless-stopped
    ports:
      - "3344:3344"
    environment:
      - PORT=3344
      - MONGODB_URI=mongodb://mongodb:27017/future-stores-cms
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRE=30d
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - supermarket-network

  frontend:
    image: ${DOCKER_USERNAME}/supermarket-frontend:latest
    container_name: supermarket-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_PORT=3344
    depends_on:
      - backend
    networks:
      - supermarket-network

volumes:
  mongodb_data:

networks:
  supermarket-network:
    driver: bridge